# Site settings
title: Cha0sX.me
email: cha0sx.coder@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Cha0s X(ian) 的博客，聊聊移动互联网、Android开发，技术与生活
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://cha0sx.me" # the base hostname & protocol for your site
weibo_username: 卡超兰度
weibo_siteurl: "http://weibo.com/zzchaos"
github_username:  Cha0sX

# Layout settings
header_type: default  # values [ drawer, default ]
post_type: highlight    # values [ highlight, default ]
pagination_type: default  # values [ ops, default ]

more_vert:
  option1:
    name: about
    link: /about/

disqus: true
disqus_shortname: 'cha0sxsblog'

# Build settings
highlighter: pygments
markdown: redcarpet  # [ maruku | rdiscount | kramdown | redcarpet ]
markdown_ext:  markdown,mkd,mkdn,md
textile_ext:   textile
redcarpet:
  extensions:
    - fenced_code_blocks
    - no_intra_emphasis
    - strikethrough
    - no_intra_emphasis
    - autolink
    - tables
    - with_toc_data